{"name": "test_login_user_invalid_data_login_error[bulka@mail.ru-]", "status": "passed", "steps": [{"name": "Login with wrong password: ", "status": "passed", "start": 1725198362264, "stop": 1725198362694}], "parameters": [{"name": "email", "value": "'bulka@mail.ru'"}, {"name": "password", "value": "''"}], "start": 1725198361958, "stop": 1725198362696, "uuid": "a917b8c1-c0a1-4abb-a7b4-9e62c3655881", "historyId": "1b13ee221665c2d9e3d59d1286a24b3a", "testCaseId": "dffb61152879fb5542bb13eac9dd1ece", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_invalid_data_login_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "MacBook-Air-Elizaveta.local"}, {"name": "thread", "value": "84379-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}], "links": [{"type": "tms", "url": "Login user with invalid data", "name": "Login user with invalid data"}]}